### ISSUE TITLE
Upgrade the @actions/core package to avoid deprecated usage

### ISSUE THREAD

**Issue by FabienFAPresta** [PostHog/check-package-version#111]
# Problem

Using the action leads to some warning about using deprecated methods.

![image](https://user-images.githubusercontent.com/112954741/200513494-e990eabf-0907-498c-a847-f0cc84576e62.png)

# Solution

We might upgrade the @actions/core package to a newer version ? Its latest is 1.10.0.

Here's a link to the npm package : https://www.npmjs.com/package/@actions/core

**Comment by dupasj** [comment]
Hi !

I don't know if this still needed but I just sent a pull request here https://github.com/PostHog/check-package-version/pull/113 to fix this issue !

Take a look to the readme ! I change the inputs/output names but I think they are more clear like that !

**Comment by humphd** [comment]
It would be great to fix these warnings.  I've tried half-a-dozen different actions tonight that all claim to be able to do what this action does, and yours is the first one that actually works!

**Comment by dupasj** [comment]
> It would be great to fix these warnings. I've tried half-a-dozen different actions tonight that all claim to be able to do what this action does, and yours is the first one that actually works!

Do you talk about my pull request [#113](https://github.com/PostHog/check-package-version/pull/113) @humphd ? If yes, do you have any problem with it ? If yes again, please fill free to add an issue on my pull request, I will try to fix it.

**Comment by ga-devfront** [comment]
@dupasj, can you explain me how to test your PR inside my GitHub Action because like @FabienFAPresta I got some warning for moment and I want to supress it :
![image](https://github.com/PostHog/check-package-version/assets/52718717/4c335a92-176d-4e36-a0ce-284c39ff041a)

**Comment by dupasj** [comment]
@ga-devfront, you can use the version of my PR [here](https://github.com/dupy-ts/check-package-version) The documentation is not 100% up to date I think, but here is the github CI that I use to be able to make eslint/typescript check, then publish (if this can help):
```
name: Node.js Package

on: [push]

jobs:
  check_typescript:
    name: Check TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check TypeScript
        run: npx tsc --noEmit
  check_eslint:
    name: Check Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check EsLint
        run: npx eslint ./src/** --quiet --ext .js,.jsx,.ts,.tsx -c ./.eslintrc.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish:
    needs: [check_typescript,check_eslint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Check package version
        id: cpv
        uses: dupy-ts/check-package-version@main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        if: steps.cpv.outputs.is-committed-version-free == 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Update package's registry
        if: steps.cpv.outputs.is-committed-version-free == 'true'
        run: echo "$(jq '.publishConfig.registry = "https://npm.pkg.github.com"' package.json)" > package.json
      - name: Publish package
        if: steps.cpv.outputs.is-committed-version-free == 'true'
        run: npm publish --@dupy-ts:registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
